##!/usr/perl
# This is a stream editor (sed) converter to make letters and reports more gender neutral
# To make this script work for a file use the following commands:
# Limitation: object pronoun & possessive adjective are the same for singular feminine (her). If the text has her it should be cross revised manually. A bang will appear next to the word to alert the reviewer. For a singular third person male the possessive adjective and the possessive pronoun are the same. A bang will appear to alert the reviewer to check the text
# chmod +x neutralise.sed
# sed -i -f neutralise.sed file.txt
# The script will go through each of these to convert them

# Pronouns
s/He's /They're! /g;
s/ He is / They are /g;
s/ he's / They're! /g;
s/ he / they /g;
s/He /They /g;
s/ him / them /g;
s/His /Their! /g;
s/ his / theirs! /g;
s/ himself is /themselves are /g;
s/ himself / themselves /g;
s/Himself /Themselves /g;
s/She's /They're! /g;
s/ she's / they're! /g;
s/She is /They are /g;
s/ she is / they are /g;
s/ she / they /g;
s/She /They /g;
s/ her / them! /g;
s/Her /Their! /g;
s/ hers / theirs /g;
s/Hers /Theirs /g;
s/ herself is / themselves are /g;
s/ herself / themselves /g;
s/Herself /Themselves /g;

# Jobs
s/ Air hostess /Flight attendant /g;
s/ air hostess / flight attendant /g;
s/ Air hostesses /Flight attendants /g;
s/ air hostesses / flight attendants /g;
s/Anchorman /Anchor person /g;
s/ anchorman/ anchor person/g;
s/Assembleyman/Assembley person/g;
s/Actress / Actor /g;
s/ actress / actor /g;
s/Businessman / Business person /g;
s/ businessman / business person /g;
s/Cameraman /Camera operator /g;
s/ cameraman / camera operator /g;
s/Chairman /Chair person /g;
s/ chairman /chair person /g;
s/Clergyman / Pastor /g;
s/ clergyman / pastor /g;
s/Congressman / Congress person /g;
s/ congressman / congress person /g;
s/Construction man /Construction worker /g;
s/ construction man / construction worker /g;
s/Council man /Council member /g;
s/ council man / council member /g;
s/Craftsman /Artisan /g;
s/ craftsman / artisan /g;
s/Crewman / Crew member /g;
s/ crewman / crew member /g;
s/Doorman /Door keeper /g;
s/ doorman / door keeper /g;
s/Fireman /Firefighter /g;
s/ fireman / firefighter /g;
s/Fire man /Firefighter /g;
s/ fire man / firefighter /g;
s/Foreman /Supervisor /g;
s/ foreman / supervisor /g;
s/Garbage man /Bin collector /g;
s/ garbage man / bin collector /g;
s/Handyman / Maintenance worker /g;
s/ handyman / maintenance worker /g;
s/Longshoreman /Stevedore /g;
s/ longshoreman / stevedore /g;
s/Mail man /Mail courier /g;
s/ mail man / mail courier /g;
s/Mailman /Mail courier /g;
s/ mailman / mail courier /g;
s/Patrolman / Police Officer /g;
s/ patrolman / police officer /g;
s/Policeman / Police Officer /g;
s/ policeman / police officer /g;
s/ police man / police officer/g;
s/Police woman / Police Officer /g;
s/ police woman / police officer /g;
s/Salesman /Salesperson /g;
s/ salesman / salesperson /g;
s/Stuntman /Stuntperson /g;
s/ stuntman / stuntperson /g;
s/Weatherman /Meteorologist /g;
s/ weatherman / meteorologist /g;
s/Anchormen /Anchor persons /g;
s/ anchormen / anchor persons /g;
s/Assembleymen/Assembley persons/g;
s/Actresses / Actors /g;
s/ actresses / actors /g;
s/Businessmen / Business persons /g;
s/ businessmen / business persons /g;
s/Cameramen /Camera operators /g;
s/ cameramen / camera operators /g;
s/Chairmen /Chair persons /g;
s/ chairmen /chair persons /g;
s/Clergymen / Pastors /g;
s/ clergymen / pastors /g;
s/Congressmen / Congress persons /g;
s/ congressmen / congress persons /g;
s/Construction men /Construction workers /g;
s/ construction men / construction workers /g;
s/Council men /Council members /g;
s/ council men / council members /g;
s/Craftsmen /Artisans /g;
s/ craftsmen / artisans /g;
s/Crewmen / Crew members /g;
s/ crewmen / crew members /g;
s/Doormen /Door keepers /g;
s/ doormen / door keepers /g;
s/Firemen /Firefighters /g;
s/ firemen / firefighters /g;
s/Fire men /Firefighters /g;
s/ fire men / firefighters /g;
s/Foremen /Supervisors /g;
s/ foremen / supervisors /g;
s/Garbage men /Bin collectors /g;
s/ garbage men / bin collectors /g;
s/Handymen / Maintenance workers /g;
s/ handymen / maintenance workers /g;
s/Layman /Layperson /g;
s/ layman / layperson /g;
s/Laymen /Laypersons /g;
s/ laymen / laypersons /g;
s/Longshoremen /Stevedores /g;
s/ longshoremen / stevedores /g;
s/Mail men /Mail couriers /g;
s/ mail men / mail couriers /g;
s/Mailmen /Mail couriers /g;
s/ mailmen / mail couriers /g;
s/Manned /Crewed /g;
s/ manned / crewed /g;
s/Patrolmen / Police Officers /g;
s/ patrolmen / police officers /g;
s/Policmen / Police Officers /g;
s/ policemen / police officers /g;
s/Police women / Police Officers /g;
s/ police women / police officers /g;
s/Salesmen /Salespersons /g;
s/ salesmen / salespersons /g;
s/Stuntmen /Stuntpersons /g;
s/ stuntmen / stuntpersons /g;
s/Waitress /Table attendant /g;
s/ waitress / table attendant /g;
s/Waitresses /Table attendants /g;
s/ waitresses / table attendants /g;
s/Weathermen /Meteorologists /g;
s/ weathermen / meteorologists /g;

# Human relationships
s/Man / Person /g;
s/ man / person /g;
s/Woman /Person /g;
s/ woman / person /g;
s/ woman/ person/g;
s/ man/ person/g;
s/Father/Parent /g;
s/Mother/Parent /g;
s/ father / parent /g;
s/ mother / parent /g;
s/ father/ parent/g;
s/ mother/ parent/g;
s/Brother/sibling/g;
s/ brother / sibling /g;
s/ brother/sibling /g;
s/Paternal/Parental/g;
s/Maternal/Parental/g;
s/ paternal / parental /g;
s/ maternal / parental /g;
s/Fathers/Parents /g;
s/Mothers/Parents /g;
s/ fathers / parents /g;
s/ mothers / parents /g;
s/ fathers/ parents/g;
s/ mothers/ parents/g;
s/Brothers/siblings/g;
s/ brothers / siblings /g;
s/ brothers/siblings /g;
s/Men / Persons /g;
s/ men / persons /g;
s/Women /Persons /g;
s/ women / persons /g;
s/ women/ persons/g;
s/ men/ persons/g;
s/Husband / Partner /g;
s/ husband / partner /g;
s/Wife / Partner /g;
s/ wife / partner/g;
s/Husbands / Partner /g;
s/ husbands / partner /g;
s/Wives / Partners /g;
s/ wives / partners /g;
s/Boyfriend / Significant other /g;
s/ bodyfriend / significant other /g;
s/Boyfriends / Significant others /g;
s/ bodyfriends / significant others /g;
s/Dude / Friend /g;
s/ dude / friend /g;
s/Dudes / Friends /g;
s/ dudes / friends /g;
s/Grandaughter /Grandchild /g;
s/ grandaughter / grandchild /g;
s/Grandaughters / grandchildren /g;
s/ grandaughters / grandchildren /g;
s/Grandson /Grandchild /g;
s/ grandson / grandchild /g;
s/Grandsons /Grandchildren /g;
s/ grandsons / grandchildren /g;
s/Son /Child /g;
s/ son / child /g;
s/Sons /Children /g;
s/ sons / children /g;
s/Daughter /Child /g;
s/ daughter / child /g;
s/Daughters /Children /g;
s/ daughters / children /g;
